$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
enabled: false
language: "en,ru"
useGitignore: true
failFast: true
dictionaryDefinitions:
  - name: "project-words"
    path: "./project-words.txt"
    addWords: true
dictionaries:
  - "project-words"
  - "python"
  - "bash"
ignorePaths:
  - "project-words.txt"
  - "ruff.toml"
  - "mkdocs.yml"
  - ".gitignore"
import:
  - "@cspell/dict-ru_ru/cspell-ext.json"
ignoreRegExpList:
  - /[^\s]{30,}/
