[beginner]
'Профиль' = """
Тут находится вся основная информация о тебе
"""

'Дом' = """
Здесь ты можешь выбрать чем хочешь заняться
"""

'Занятия' = """
В игре есть 4 занятся: работа, прогулка, сон и игра

Подробно про них можешь посмотреть в категории <code>Для новичков</code>

*Занятся несколькими деламы нельзя
"""

'Работа' = """
Работа - это одна из основных способов дохода. Чем больше уровень, тем больше бабла сможешь заработать. Кроме бабла ты ещё получаешь и опыт

Работать можно каждые 3 часа
"""

'Прогулка' = """
Отправляйся на прогулку, получай лут и опыт

Во время прогулки можно найти встретить мобов (за 1 прогулку можно встретить только 1 моба)

Лут зависит от погоды. Чтобы его узнать напиши команду <code>погода</code> (<code>/weather</code>)

Если у тебя есть собака, то можно получить больше лута и хп
"""

'Сон' = """
Сон длится от 3 до 8 часов

После сна ты востанавлываешь усталось и получаешь опыт (от 1.5 до 2)
"""

'Игра' = """
Время игры длится от 15 минут до 3 часов

После игры ты востанавлываешь настроение и получаешь опыт (от 3.5 до 5.7)
"""

'Перекидка' = """
Чтобы передавать предметы надо использовать команду <code>/transfer {имя предмета} {количество}</code>

В место <code>/transfer</code> можно написать <code>передать</code>
"""

'Прокачка' = """
Чтобы поднять свой уровень надо заработать опыта. Опыт можно получить во время работы, прогулки и крафта

За каждый лвл можно получить бокс 📦
"""

'Магазин' = """
Магазин - место где можно купить любые предметы

Чтобы посмотреть список продуктов надо просто написать <code>/shop</code>, а чтобы купить продукт надо написать <code>/shop {имя предмета} {количество}</code>

Вместо <code>/shop</code> можно написать шоп
"""

'Крафтинг' = """
Тут ты можешь скрафтить придметы и получать опыт
Чтобы скрафтить нужно написать <code>/craft {предмет} {кол-во}</code>

В место <code>/craft</code> можно написать <code>крафт</code>
"""

'Квесты' = """
Тут все просто. Нужно собирать определенные приметы. За это ты получишь бабло и опыт. Квест можно пропустить, но за это нужно заплатить, с каждым разом цена увеличивается 
"""

[advanced]
'Казино' = """
Хочешь легких денег?

Ты по адресу, шансы на победу 50%

Чтобы сыграть нужно иметь билет 🎟
"""

'Реферальная система' = """
За приглашения друзей ты получишь бабло (от 5к до 15к) и бокс (от 1 до 2)

Чтобы создать реферальную ссылку, напиши команду <code>/ref</code>

Отправь эту ссылку своим друзьям и знакомым, а как только они перейдут по ссылке ты получишь свое бабло
"""

'Промокоды' = """
Чтобы использовать надо написать <code>/promo {имя промокода}</code>

При использовании ты получишь много крутого лута (наверно)
"""

'Обменник' = """
Обменник доступен с 5 уровня

Тут можно обменять свои приметы на бабло. Предмет выбирается раз в 24 часа

Чтобы обменять, нужно написать <code>/exchanger {кол-во}</code>
"""

[other]
'Ивент' = """
Соберай 🦋 и побеждай
Бабочек можно получать во время прогулки, в боксе и в сундуке

Ивент будет длится до 01.06.2024
"""
