line-length = 100
indent-width = 4

target-version = "py311"


[lint]
select = ["E4", "E7", "E9", "F", "I", "N", "TD", "RUF"]
ignore = ["N818", "TD002", "TD003", "RUF001"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.isort]
combine-as-imports = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = "dynamic"
