version: "3"

tasks:
  default:
    - task: lint
    - task: fix
    - task: spell-check
    - task: format

  run:
    cmd: bash ./run.sh

  stop:
    ignore_error: true
    cmds:
      - kill $(cat .pid)
      - rm .pid

  lint:
    vars:
      paths: "{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}src/ tools/{{end}}"
    cmds:
      - ruff check --respect-gitignore {{.paths}}
      - pylint -f colorized {{.paths}}
      - pyright {{.paths}}

  format:
    ignore_error: true
    cmd: ruff format --respect-gitignore src tools

  fix:
    cmd: ruff check --respect-gitignore --fix src tools

  spell-check:
    vars:
      paths: "{{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}"
    cmd: cspell lint {{.paths}}

  dev-install:
    cmds:
      - uv pip install --upgrade -r requirements.txt
      - uv pip install --upgrade ruff pyright pre-commit pylint watchfiles
      - uv pip install "changelog-parser @ git+https://github.com/0xM4LL0C/changelog-parser@main"
      - npm install -g cspell @cspell/dict-ru_ru
      - cspell link add @cspell/dict-ru_ru

  dev-setup:
    deps:
      - dev-install
      - create-config
    cmds:
      - pre-commit install

  clean:
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - rm -rf nohup.out .pid site .*_cache release_body.md *.log

  create-config:
    ignore_error: true
    cmd: python3 tools/create_config.py

  docs-setup:
    cmds:
      - pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin transliterate python-slugify

  release:
    cmd: python3 tools/release.py {{.CLI_ARGS}}

  scan-comments:
    cmd: rg -I -n -H -e "# TODO" -e "# FIXME" -e "# NOTE" --glob "!Taskfile.yml" --ignore-file .gitignore || true

  dev-run:
    cmd: watchfiles "python3 src/main.py --debug --no-interactive" src

  install:
    cmds:
      - ./install.sh
