name: Checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.py"
    

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dev requitements
      run: make dev-install
    
    - name: lint
      run: make lint
