name: Checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - ".github/workflows/check.yml"
    

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install requirements
      run: | 
        pip install -r requirements.txt
        pip install git+https://github.com/HamletSargsyan/changelog-parser.git

    - name: test
      run: python -c "import changelog; print(changelog.__version__)"

    - name: Install dev requitements
      run: make dev-install
    
    - name: lint
      run: make lint
