name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**.md"
      - "mkdocs.yml"
      - ".github/workflows/documentation.yml"
      - "README.md"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - run: task docs-setup
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy
