name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**.md"
      - "mkdocs.yml"
      - ".github/workflows/documentation.yml"
      - "README.md"
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-material
      - run: rm -rf docs/index.md && cp README.md docs/index.md
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy
