name: Create Release

on:
  push:
    tags:
      - 'v*'


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - run: pip install -r requirements.txt
    - run: python tools/get_release_body.py > release_body.md

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref }}
        body_path: "release_body.md"
        draft: false
        prerelease: false



    - name: Send release notification
      run: python tools/send_release_notification.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
